name: ${COMPOSE_PROJECT_NAME}
services:
   nginx:
     build: ./docker/nginx
     container_name: ${COMPOSE_PROJECT_NAME}-${NGINX_CONTAINER_NAME}
     volumes:
         - ./app:/var/www/html/
         - ./logs/nginx:/var/log/nginx/
         - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
     networks:
       my_net:
         ipv4_address: 192.168.2.5
     ports:
       - 80:80
     restart: always
     depends_on:
       - php
       - db

   php:
     build: ./docker/php
     container_name: ${COMPOSE_PROJECT_NAME}-${PHP_CONTAINER_NAME}
     expose:
       - 9000
     networks:
       my_net:
         ipv4_address: 192.168.2.10
     volumes:
        - ./app:/var/www/html/
        - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ./logs/php.log:/var/log/fpm-php.www.log

   db:
    build: ./docker/db
    container_name: ${COMPOSE_PROJECT_NAME}-${DB_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      my_net:
        ipv4_address: 192.168.2.8
    ports:
      - 5432:5432
networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
