name: "site"
services:
   nginx:
     image: nginx
     volumes:
         - .:/var/www/html/
         - ./logs/nginx:/var/log/nginx/
         - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
     ports:
       - 80:80
     restart: always
     depends_on:
       - php
       - db

   php:
     build: ./docker/php
     expose:
       - 9000
     volumes:
        - .:/var/www/html/
        - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ./logs/php.log:/var/log/fpm-php.www.log

   db:
    build: ./docker/db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432